### PR TITLE
Refactor traits

### PR DESCRIPTION
**Pull request by M-Adoo**
After discuss in #62, we decide to some refactoring:

- [x] 1.  `Observable` should split into  concrete type, not only use a `Observable` struct to wrap all.
     - [x] rename `Observable` to `ObservableFromFn` #67 
     - [x] `Observable` create functions return  concrete class like `ObservableRange `.  #73 
- [x] 2. rename `RawSubscribable` to `Observable`, and change the trait define to #69 
```rust
pub trait Observable<O, U: SubscriptionLike> {
  /// A type implementing [`SubscriptionLike`]
  type Unsub: SubscriptionLike;
  fn actual_subscribe(self, subscriber: Subscriber<O, U>) -> Self::Unsub;
}
```
- [ ] 3. Add bounds to operator struct generics.
- [x] 4. Use `Drop` to improve Subscription manage. #70 
- [ ] 5. Operators as provided methods on Observable instead of extension traits.

### CODE REVIEW

File: CHANGELOG.md [hunk 1]
```diff
@@ -1,5 +1,17 @@
...
+### Features
+- **operator**: add `take_last` operator.
+
+### Refactor
+
+- **observable**: Observable split into many concrete type, not only use a Observable struct to wrap all, every observable creating function has a concrete type.
+
+### Breaking Changes
+
+- **observable**: remove `Observable::new`, and add a same `create` function in `observable` to replace it.
```
Comment (helgoboss) [inline CHANGELOG.md]: I noticed you prefer `observable::create` over `Observable::create`. There's nothing wrong with that and it looks clean to me but it is different from probably most other Rx implementations where `create` is a static method on the main `Observable` class (even in `RxCpp` although in C++ free factory functions are usually preferred over static class factory methods). I think the idea there is to have a kind of main class/trait (`Observable`) and make most things accessible from there - which improves API convenience. Just an observation, I don't have any hard opinion on that.

**Comment by helgoboss** [comment]
Do you have any idea how I could help here apart from doing reviews? Seems hard to work on that in parallel as it would just cause merging trouble.

File: CHANGELOG.md (hunk 1 above)
Comment (M-Adoo) [reply CHANGELOG.md]: We keep all creating Observable functions as function now. And after `Operators as provided methods on Observable instead of extension traits` finished,  We can discuss if those functions also provide on Observable.

**Comment by M-Adoo** [comment]
> Do you have any idea how I could help here apart from doing reviews? Seems hard to work on that in parallel as it would just cause merging trouble.

I think `Use Drop to improve Subscription manage` and ` Operators as provided methods on Observable instead of extension traits` can work in parallel.  And others all big change,  we can create a mr and list operators  and ensure not work on same op at the same time.

**Comment by M-Adoo** [comment]
@helgoboss Do you wan to handle task 5,  after it finished, task 3 auto resolve.

**Comment by helgoboss** [comment]
> @helgoboss Do you wan to handle task 5, after it finished, task 3 auto resolve.

Okay, I'll do it today or tomorrow.

**Comment by M-Adoo** [comment]
I'll work on task 4 and task 1.2, if i have time this weekend.

**Comment by helgoboss** [comment]
I thought task 5 is straight-forward but there are some issues I didn't expect. Will get back to you tomorrow.

**Comment by helgoboss** [comment]
@M-Adoo Now about the issues I had with task 5: Do you have any idea how to solve the `error[E0282]: type annotations needed` which occurs when moving `take_last()` to `Observable`? https://github.com/helgoboss/rxRust/commit/a1a5629dd4535dcbe7edbaadad74d65f9cc70ac0

This issue occurs also with other operators if they are used in certain constellations (after making them a provided method on `Observable`). I hope I'm missing something obvious. If not, maybe this task will be easier to do after having sorted out #71 ... what do you think?

**Comment by M-Adoo** [comment]
> @M-Adoo Now about the issues I had with task 5: Do you have any idea how to solve the `error[E0282]: type annotations needed` which occurs when moving `take_last()` to `Observable`? [helgoboss@a1a5629](https://github.com/helgoboss/rxRust/commit/a1a5629dd4535dcbe7edbaadad74d65f9cc70ac0)
> 
> This issue occurs also with other operators if they are used in certain constellations (after making them a provided method on `Observable`). I hope I'm missing something obvious. If not, maybe this task will be easier to do after having sorted out #71 ... what do you think?

You are right, we should solve #71  first. So sad.
